library(multtest)
library(gplots)
library(LDheatmap)
library(genetics)
library(ape)
library(EMMREML)
library(compiler)
library(scatterplot3d)
library(grid)
library(bigmemory)
library(nloptr)
library(snpStats)
library(Matrix)
library(rgl)
source("/GAPIT/GAPIT.library.R")
source("/GAPIT/gapit_functions.txt")
args = commandArgs(trailingOnly=TRUE)
setwd(args[3])
myVCF <- read.table(args[1], head = FALSE) 
myTRAIT <- read.table(args[2], head = TRUE)
myGAPIT_mutiple <- GAPIT(Y=myTRAIT,G=myVCF,PCA.total=3, model="MLM", Multiple_analysis=F)
